[plugin]
name = "safety-lite"
author = "Unknown Developer"
version = "0.1.0"
language = "lua"
version_required = "1.2.4"

[settings]
# If you are on any of the servers here, Safety will not run.
WhitelistedIPs = []

BlockedConcommands = [
	"+voicerecord", "-voicerecord", "retry",
	"startmovie", "endmovie", "playdemo",
	"play", "exit", "developer",
	"disconnect", "showscores", "mat_specular",
	"cl_timeout", "sendrcon", "fov",
	"screenshot", "ping", "record",
	"jpeg", "kickme", "gmod_mcore_test",
	"achievementRefresh", "ScreengrabRequest", "Progress"
]

BlockedNetMessages = [
	"ash_ban", "pac_to_contraption", "pac_modify_movement",
	"pac_projectile", "pac.AllowPlayerButtons", "pac_request_precache",
	"pac_setmodel", "pac_update_playerfilter", "pac_footstep",
	"pac_in_editor"
]

# URL Whitelist
PatternURLWhitelist = [
	"%w+%.sndcdn%.com/.+",
	"%w+%.dl%.dropboxusercontent%.com/(.+)",
	"cdn[%w-_]*%.discordapp%.com/.+"
]

SimpleURLWhitelist = [
	"translate.google.com", "yp.shoutcast.com", "dl.dropboxusercontent.com",
	"dl.dropbox.com", "google.com", "gitlab.com",
	"github.com", "raw.github.com", "raw.githubusercontent.com",
	"gist.githubusercontent.com", "dropbox.com", "dl.dropbox.com",
	"api.github.com"
]

# Lua Files Blacklist
BlockedLuaFiles = [
    "autorun/pac_core_init%.lua$",
    "autorun/pac_editor_init%.lua$",
    "autorun/pac_extra_init%.lua$",
    "autorun/pac_init%.lua$",
    "autorun/pac_restart%.lua$",
    "autorun/pac_version%.lua$"
]
